---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# roamR

The R wrapper package for the [Roam Backend API (beta)](https://roamresearch.com/#/app/developer-documentation/page/W4Po8pcHQ)!!

<!-- badges: start -->

<!-- badges: end -->

## Installation

You can install the development version of `roamR` with:

``` r
# install.packages("devtools")
devtools::install_github("kleinlennart/roamR")
```

## API Key

See <https://roamresearch.com/#/app/developer-documentation/page/W4Po8pcHQ> on how to get your **API Key**.

As of now, you have to sign in here to export it: <https://relemma-git-feat-frontdesk.roamresearch.com/#/app>

## Example

```{r example, eval = FALSE}
library(roamR)

# Set your credentials
set_roam_creds()

# Alternatively:
Sys.setenv(ROAM_GRAPH = "<YOUR-GRAPH-NAME>")
Sys.setenv(ROAM_API_KEY = "<YOUR-API-KEY>")


# get all pages in the graph as a tibble
pages <- req_roam(
  query = "[:find ?id ?uid ?title :where [?id :node/title ?title][?id :block/uid ?uid]]",   set_names = TRUE
)

```
